# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bcd4762ad0fe16ed243d9ef0726f3c3793535b0e19375a19016c4fc34e70c54bb6ef537fadf2626aa0972d96574bc2f5a1640c399e736edcadfc0f66c3ea643b

test:
  secret_key_base: b9447c7bd15be979c63b8cf6c59df014b6ac038a798693ea2958a32763e07e79265a70caf0d04551671428d4c76719b7ded8933083a8bfcb5df40930be34cd41

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
